# Generated by Django 4.2.5 on 2023-09-22 09:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='release_date')),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('release_date', models.DateField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='movies_app', to='movies_app.actor')),
                ('director', models.ManyToManyField(related_name='movies_app', to='movies_app.director')),
                ('genres', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['-release_date'], name='movies_app__release_28eaaa_idx')],
            },
        ),
    ]
